/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Product = IDL.Record({
  'id' : IDL.Nat,
  'inStock' : IDL.Bool,
  'originalPrice' : IDL.Float64,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
});

export const idlService = IDL.Service({
  'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
  'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'inStock' : IDL.Bool,
    'originalPrice' : IDL.Float64,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
  });
  
  return IDL.Service({
    'getProduct' : IDL.Func([IDL.Nat], [IDL.Opt(Product)], ['query']),
    'getProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };